// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/mcpplane/handoff"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// ConsumeOnGET provides a mock function for the type MockHandler
func (_mock *MockHandler) ConsumeOnGET() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConsumeOnGET")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockHandler_ConsumeOnGET_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeOnGET'
type MockHandler_ConsumeOnGET_Call struct {
	*mock.Call
}

// ConsumeOnGET is a helper method to define mock.On call
func (_e *MockHandler_Expecter) ConsumeOnGET() *MockHandler_ConsumeOnGET_Call {
	return &MockHandler_ConsumeOnGET_Call{Call: _e.mock.On("ConsumeOnGET")}
}

func (_c *MockHandler_ConsumeOnGET_Call) Run(run func()) *MockHandler_ConsumeOnGET_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_ConsumeOnGET_Call) Return(b bool) *MockHandler_ConsumeOnGET_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockHandler_ConsumeOnGET_Call) RunAndReturn(run func() bool) *MockHandler_ConsumeOnGET_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumePOST provides a mock function for the type MockHandler
func (_mock *MockHandler) ConsumePOST(w http.ResponseWriter, r *http.Request, token string, item *handoff.Item) bool {
	ret := _mock.Called(w, r, token, item)

	if len(ret) == 0 {
		panic("no return value specified for ConsumePOST")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, string, *handoff.Item) bool); ok {
		r0 = returnFunc(w, r, token, item)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockHandler_ConsumePOST_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumePOST'
type MockHandler_ConsumePOST_Call struct {
	*mock.Call
}

// ConsumePOST is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - token string
//   - item *handoff.Item
func (_e *MockHandler_Expecter) ConsumePOST(w any, r any, token any, item any) *MockHandler_ConsumePOST_Call {
	return &MockHandler_ConsumePOST_Call{Call: _e.mock.On("ConsumePOST", w, r, token, item)}
}

func (_c *MockHandler_ConsumePOST_Call) Run(run func(w http.ResponseWriter, r *http.Request, token string, item *handoff.Item)) *MockHandler_ConsumePOST_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *handoff.Item
		if args[3] != nil {
			arg3 = args[3].(*handoff.Item)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHandler_ConsumePOST_Call) Return(consumed bool) *MockHandler_ConsumePOST_Call {
	_c.Call.Return(consumed)
	return _c
}

func (_c *MockHandler_ConsumePOST_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, token string, item *handoff.Item) bool) *MockHandler_ConsumePOST_Call {
	_c.Call.Return(run)
	return _c
}

// RenderGET provides a mock function for the type MockHandler
func (_mock *MockHandler) RenderGET(w http.ResponseWriter, r *http.Request, token string, item *handoff.Item) {
	_mock.Called(w, r, token, item)
	return
}

// MockHandler_RenderGET_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderGET'
type MockHandler_RenderGET_Call struct {
	*mock.Call
}

// RenderGET is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - token string
//   - item *handoff.Item
func (_e *MockHandler_Expecter) RenderGET(w any, r any, token any, item any) *MockHandler_RenderGET_Call {
	return &MockHandler_RenderGET_Call{Call: _e.mock.On("RenderGET", w, r, token, item)}
}

func (_c *MockHandler_RenderGET_Call) Run(run func(w http.ResponseWriter, r *http.Request, token string, item *handoff.Item)) *MockHandler_RenderGET_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *handoff.Item
		if args[3] != nil {
			arg3 = args[3].(*handoff.Item)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHandler_RenderGET_Call) Return() *MockHandler_RenderGET_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_RenderGET_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, token string, item *handoff.Item)) *MockHandler_RenderGET_Call {
	_c.Run(run)
	return _c
}
