// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/mcpplane/model"
)

// NewMockAppCatalog creates a new instance of MockAppCatalog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppCatalog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppCatalog {
	mock := &MockAppCatalog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppCatalog is an autogenerated mock type for the AppCatalog type
type MockAppCatalog struct {
	mock.Mock
}

type MockAppCatalog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppCatalog) EXPECT() *MockAppCatalog_Expecter {
	return &MockAppCatalog_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockAppCatalog
func (_mock *MockAppCatalog) Get(name string) (*model.ToolEntry, bool) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.ToolEntry
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (*model.ToolEntry, bool)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.ToolEntry); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ToolEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockAppCatalog_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAppCatalog_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - name string
func (_e *MockAppCatalog_Expecter) Get(name any) *MockAppCatalog_Get_Call {
	return &MockAppCatalog_Get_Call{Call: _e.mock.On("Get", name)}
}

func (_c *MockAppCatalog_Get_Call) Run(run func(name string)) *MockAppCatalog_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppCatalog_Get_Call) Return(toolEntry *model.ToolEntry, b bool) *MockAppCatalog_Get_Call {
	_c.Call.Return(toolEntry, b)
	return _c
}

func (_c *MockAppCatalog_Get_Call) RunAndReturn(run func(name string) (*model.ToolEntry, bool)) *MockAppCatalog_Get_Call {
	_c.Call.Return(run)
	return _c
}
